kumuluzee:
  name: gameplay-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://20.240.34.248/gameplay
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/GameplayDS
      connection-url: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/gameplay?sslmode=require
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/GameplayDS
  metrics:
    web-instrumentation:
      - name: gameplay-endpoint
        url-pattern: /v1/images/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="gameplay" status="ERROR">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="7092a7de-fa02-46f5-a10c-36378f703b7f-ls.logit.io"
                                    port="21104" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  broken: false

